let PAN_SENSITIVITY = 0.01;
let ZOOM_SENSITIVITY = 0.001;
let ZOOM_EXPONENT_MAX = 10;
let ZOOM_EXPONENT_MIN = -10;
let MOVEMENT_SPEED_FACTOR = 3;
let SEED = 'sus';
let TIME_RATE_BASE = 1;
let GRAV_STRENGTH = 1;
let GRAV_DIST_LOWER_LIMIT = 1;
let MAX_TIME_STEP = 0.015;
let MIN_TIME_RATE_EXPONENT_INT = -10;
let MAX_TIME_RATE_EXPONENT_INT = 10;
let TIME_RATE_EXPONENT_STEP = 0.5;
let TIME_RATE_EXPONENT_BASE = 0;
let TIME_ACCEL_RATES = [1, 3, 10, 30, 100, 300, 1000, 3000, 10000];
let FIXED_TIME_STEP_FACTOR = 0.01;

let SCENARIOS = [
  /*
  [
    [mass, color, density, x, y, z, vx, vy, vz],
  ]
  */
];
